version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - api-server

  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./.tenet:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/tenet.db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -P solo
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
